### ISSUE TITLE
Builder: Publish endpoint can throw a 500 when package.yaml is invalid

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#222]
If the package.yaml is malformed in some specific ways the API will raise an exception and throw a 500 rather than handling the error properly and returning a 400.  For example, if someone were attempting to add a new function, but doesn't properly indent the start of the entry:

```yaml
    - name: num_chars
      summary: Returns the number of characters in given file
      display_name: Number of Characters
      description: Returns the number of characters in given file
      return_type: integer
      parameters:
        - name: file
          display_name: File
          summary: File to measure
          description: Input file that will be measured
          type:  file
          required: true
      # This is under-indented
      - name: parameter_types
        summary: Test for parameter type form rendering and passthrough values
        display_name: Parameter Types
        parameters:
          - name: boolean
            type: boolean
            required: False
```

All such errors should be handled gracefully with as useful of a response back to the user as we can muster.
