### ISSUE TITLE
define initial yaml schema for packages and functions

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#3]
The yaml in this description represents the current state of the schema.  It should be updated to reflect any changes that come out of discussion in the issue (or elsewhere).

```yaml
# (required): schema version for the package portion of the yaml. This would inform which serializer / parser
# to use in the event that we needed to make breaking changes to the way packages are defined.
version: string
package:
  # (required) human-friendly unique identifier (team + package name must be unique)
  name: string

  # (optional) Defaults to name.  While name must stay constant so that the internal package record can be identified, this can be changed to update how the name is displayed.
  display_name: string

  # (optional) Detailed description
  description: string

  # (required) Language that the functions are written in
  language: string

  # (optional) Defaults to {name}.{ext}, e.g. mypackage.py.  (not totally convinced this needs to be configurable)
  filename: string

  # (optional) Environment variables to set when running any functions in the package
  # TODO: Determine syntax for setting value from a pre-configured secret
  environment:
      ENV_VARIABLE: value
  
  # (required)
  functions:
    # Similar to package level fields, but for the function
    - name: string
      display_name: string
      description: string

      # (required) Parameters that the function takes
      parameters:
        # These are mostly self-explanatory.  See package descriptions where appropriate.
        - name: string
          display_name: string
          description: string
          # TODO: Determine valid type options, what those map to in any given language, and what they map to in OpenAPI
		  type:  string
          default: string | int
          required: bool

          # (optional) Enumerate valid input options
          options:
            - name: string
              value: string | int
```
