### ISSUE TITLE
Misc Package Creation Updates

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#55]
Some miscellaneous outstanding updates that are needed to the "package create" command in the CLI:

* The language should be a required argument.  Right now if you don't specify a language, it defaults to python.  This gives python a different status than other languages, which is not what we're going for.
* The yaml file that gets created should be named `package.yaml`, rather than `<package_name>.yaml`
* The `package.yaml` format needs to be updated to reflect the current schema.  We should fill out the package name and have examples / descriptors for the remaining stuff.
* It might be nice to have "next steps" output after creating the package.  So something like:
  ```
  $ functionary package create -l python somethinguseful

  Package something useful created at <path to somethinguseful>

  Next steps:
  * Write your functions in the generated functions.py
  * Update the package.yaml with your package and function information
  * When ready, publish the package to your environment by running:
          functionary package publish <path to somethinguseful>
  ```
  Make good use of color and other formatting to dress that up as you see fit.

**Comment by scott-taubman** [comment]
The package.yaml that gets generated should look something like this:

```yaml
# (required): schema version for the package definition
version: "1.0"
package:
  # (required) human-friendly unique identifier; cannot be changed
  name: <package name>    <-- Fill this in based on the name provided to the create command

#   # (optional) defaults to name; determines how the package is displayed in the UI
#   display_name: string

#   # (optional) detailed description
#   description: string

  # (required) language that the functions are written in
  language: <language>  <-- Fill this in based on the laguage provided to the create command

  functions:
#    # similar to package level fields, but for the function
#    - name: string
#      display_name: string
#      description: string

#      # (required) Parameters that the function takes
#      parameters:
#          # (required) should match the name of the parameter in the actual function signature
#        - name: string
#          # (optional) defaults to name; determines how the parameter is displayed in the UI
#          display_name: string
#          # (optional) detailed description
#          description: string
#          # (required) data type of the parameter     <-- list of valid types TBD, so leave it at this for now
#          type:  string
#          # (optional) default value that will be used if none is provided
#          default: string | num
#          # (optional) whether the parameter is required
#          required: bool

#          # (optional) enumerate valid input options
#          options:
#            - name: string
#              value: string | num
```
