### ISSUE TITLE
Dynamically generate functions portion of package.yaml

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#62]
Some portions of the function definitions that must be defined in the package.yaml could be generated based on the function signatures in the functions.py.  There should be a command available in the CLI that updates the package.yaml for you with whatever it can glean from those functions.

For example.  Let's say my functions.py looks like this:

```python
def add(x: float, y: float = 5.0):
    """Adds two numbers"""
    pass

def repeat(word: str, count: int = 2, loud: bool = False):
    """Repeat a word, possibly often, possibly loudly"""
    pass
```

The goal is to be able to run a command like:

```shell
functionary package genschema /path/my/package
```

And update the functions portion of our package.yaml to look like:

```yaml
  functions:
    - name: add
      description: Adds two numbers
      parameters:
        - name: x
          type: float
          required: true
        - name: y
          type: float
          default: 5.0
          required: false
    - name: repeat
      description: Repeat a word, possibly often, possibly loudly
      parameters:
        - name: word
          type: string
          required: true
        - name: count
          type: int
          default: 2
          required: false
        - name: loud
          type: bool
          default: false
          required: false
```
